### ISSUE TITLE
Missing Issue Descriptions

### ISSUE THREAD

**Issue by SupaFresh** [evandixon/SkyEditor.ROMEditor#83]
Many Issues have no Description on GitHub. That makes it hard to understand what the issues are and as a result makes it harder for contributers to identify and help fix the issues. Please add descriptions to issues that are missing descriptions.

**Comment by evandixon** [comment]
Sorry about that. Most of the time when this happens, it's so I can get an idea in my head somewhere a little more permanent before it goes away. I'll try to do better in the future.

**Comment by SupaFresh** [comment]
Ok thank you!
