### ISSUE TITLE
(PSMD) Portrait and starters mods conflict

### ISSUE THREAD

**Issue by Remiccino** [evandixon/SkyEditor.ROMEditor#87]
I wanted to change starters and modify their portraits at the same time, so I created 2 projects, a Portrait mod and a Starters mod within one solution. But when I built the ROM, the starters mod worked while the portraits all became corrupted: 

https://media.discordapp.net/attachments/378799663018672129/457148344767348737/unknown.png

Later, I found out the Starter mod also extract its own copy of the portraits, so I tried editing the portraits in there, to no avail as they are replaced by the first 3 pre-made ones.
So in the end, I had to do the starters mod, then build a portrait mod upon the modded ROM again. This is unnecessarily painstaking.

Thereby I suggest allowing editing of portraits within the starter mod, or making the starter mod fetching the portraits from the portrait mod if both exist within the same solution.

**Comment by evandixon** [comment]
I'll work on fixing it when I can (I won't be able to even start until the 25th of this month), but as a quick fix, go to (Solution Directory)/(Starter Mod Project Directory)/Raw Files/romfs, and delete face_graphic.bin. (Do _not_ delete the file from the BaseROM project.) When building the solution, this file will not be included in the starter mod patch, so you'll see all of the game's placeholder portraits, and you should be able to use the portraits from your other project.
