### ISSUE TITLE
Stat boosts in fixed_pokemon.bin are misplaced

### ISSUE THREAD

**Issue by Remiccino** [evandixon/SkyEditor.ROMEditor#96]
As the title says, the Defense and Sp.Attack boosts in the fixed_pokemon.bin editor are swapped. Here are screenshots for reference.

![image](https://user-images.githubusercontent.com/33729347/43496322-0375f0f0-9567-11e8-96f3-cbeffde6c49a.png)
![image](https://user-images.githubusercontent.com/33729347/43496379-552ce958-9567-11e8-8063-269597a71a17.png)

**Comment by evandixon** [comment]
Good catch! Thanks for reporting!
